import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { cn } from '@/shared/utils/utils'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const norms = localFont({
  src: [
    { path: '../shared/assets/fonts/norms/400.woff2', weight: '400' },
    { path: '../shared/assets/fonts/norms/500.woff2', weight: '500' },
    { path: '../shared/assets/fonts/norms/700.woff2', weight: '700' },
  ],
  display: 'swap',
  variable: '--font-norms',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={cn(norms.variable, 'font-sans')}>{children}</body>
    </html>
  )
}
